# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chencheng's Blog
email: charles.cc.zhang@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am basically an Embedded Linux Developer.
  But I work on many other things as well.
  This blog is a place where I share my thoughts and experiences.
# twitter_username: username
github_username: swechencheng
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Stockholm # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-spaceship

author:
  name   : "Chencheng Zhang"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "An Embedded Linux Developer living in Sweden."
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/chenchengzhang/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/swechencheng/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/swchencheng/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

jekyll-spaceship:
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  media-processor:
    default:
      width: 800px
      height: 450px
      style: 'aspect-ratio: 16/9; max-width: 800px; max-height: 450px; margin: 0 auto;'
      allowfullscreen: true
